export const basicTokenData = {
  id: "",
  creator: "",
  user: {
    name: "",
    description: "",
    walletAddress: "",
    profilePicture: "",
  },
  name: "",
  ticker: "",
  description: "",
  tokenMint: "",
  tokenPrivate: "",
  isLiquidityAdded: false,
  date: "",
  imgUrl: "",
  totalComments: 0,
  marketCap: 0,
  comments: 0,
  createdAt: "",
  tokenFee: 0,
  maxTokenFee: 0,
  seed: String(process.env.NEXT_PUBLIC_SEED),
};
